module.exports = {
  TOKEN_REQUIRED: "Token required.",
  TOKEN_NOT_MATCHED: "Invalid Token.",
  UNAUTHORIZED_USER: "You are unauthorized.",
  EMAIL_NOT_FOUND: "Email not found.",
  SUCCESS: "Success.",
  INCORRECT_PASSWORD: "Password is incorrect.",
  USER_INACTIVE:
    "You account is deactived, Please contact to Admin for more information.",
  INTERNAL_SERVER_ERROR: "Internal server error.",
  EMAIL_SENT_SUCCESSFULLY: "Email sent successfully.",
  SOMETHING_WENT_WRONG: "Something went wrong. Please try again later.",
  ADMIN_UPDATED: "Your profile has been updated successfully.",
  LOGIN_SUCCESS: "Login successfully.",
  PASSWORD_RESET: "Your password reset successfully.",
  PASSWORD_CHANGED: "Your password changed successfully.",
  INCORRECT_OLD_PASSWORD: "Old password is incorrect.",
  STATIC_PAGE_LIST: "Static page has been fetched successfully.",
  STATIC_PAGE_NOT_FOUND: "Static page not found.",
  LOGOUT_SUCCESS: "Logged out successfully.",
  LOGOUT_FAIL: "Logout Unsuccessful error in deleting user in DB.",
  USER_NOT_FOUND: "User not found.",
  EMAIL_ALREADY_REGISTERED: "Email already registered.",
  REGISTER_SUCCESS: "You have registered successfully.",
  VERIFICATION_SUCCESS: "Verified successfully.",
  PASSWORD_FAIL: "Password updation failed.",
  EVENT_ALREADY_EXIST: "Event with same title already exists.",
  EVENT_SUCCESS: "Event created successfully.",
  INVALID_OTP: "Invalid OTP.",
  OTP_EXPIRED: "OTP Expired.",
  VERIFICATION_SUCCESSFUL: "OTP verified successfully.",
  NO_RECORD_FOUND: "No records found.",
  ROLE_NOT_FOUND: "No such role found with provided Id.",
  EVENT_NOT_FOUND: "No events found.",
  INVALID_PARAMS: "Invalid request parameters.",
  NO_CLUB_ASSOCIATED: "No club is associated with the club admin.",
  NO_PERMISSIONS:
    "You do not have the necessary permissions to access this module.",
  COACH_NOT_FOUND: "Coach not found.",
  TEAM_NOT_FOUND: "Team not found.",
  CLUB_ADMIN_NOT_ASSOCIATED_WITH_TEAM:
    "Club admin does not manage the club associated with the team.",
  REQUESTS_EXISTS: "Request for this already exist.",
  REQUEST_SUCCESSFUL: "Request created successfully.",
  REQUEST_NOT_FOUND: "Request not found.",
  REQUEST_HANDLED: "Request handled successfully.",
  PLAYER_NOT_FOUND: "Player not found.",
  COACH_NOT_ASSOCIATED_WITH_TEAM:
    "Assigned Coach is not associated with particular team.",
  REQUEST_ALREADY_HANDLED: "Request already handled earlier.",
  REASON_FOR_REJECTED: "Reason for rejection is compulary.",
  EVENT_TIME_TEAM_SAME:
    "Event having same teams during this time duration already exists.",
  RECORD_SUCCESS: "Rrecord created successfully.",
  RECORD_EXISTS: "Record with this email already exists.",
};
